### ISSUE TITLE
German Characters

### ISSUE THREAD

**Issue by aschi2403** [RickStrahl/Westwind.AspNetCore.Markdown#12]
There seems to be a problem with german characters.
I think they don't get parsed how they should be, because if I write them directly in an ASP.NET Core Web Razor Page they are displayed correctly in the browser.
When I write them in the Markdown file they are shown as random characters like in the screenshot attached.
I would really appreciate if you could fix that, or tell me if I did something wrong in which case I'm sorry I created a Github issue for that.

![image](https://user-images.githubusercontent.com/38920497/65060451-27e2f900-d978-11e9-8829-3015a84b4901.png)
![image](https://user-images.githubusercontent.com/38920497/65060479-39c49c00-d978-11e9-9221-79d8ecfb58a3.png)
![image](https://user-images.githubusercontent.com/38920497/65060506-4812b800-d978-11e9-82ce-36c324e12458.png)

**Comment by RickStrahl** [comment]
Most likely that's an encoding problem. Make sure that the file is UTF-8 encoded. Otherwise you need to use the low level functions and specify the encoding to use.

Checked in the sample:

```html
<div class="sample-block">
    <markdown Filename="~/MarkdownPartialPage.md"></markdown>
</div>
```
then add:

```md
# Inhalt

Überschrift
```


Run it and:

![image](https://user-images.githubusercontent.com/1374013/65066324-06165180-d939-11e9-9596-316efa277d9e.png)

**Comment by aschi2403** [comment]
Thanks for you answer, it really was an Encoding problem. 
For some reason when I opened the Markdown file  in Visual Studio Code it showed UTF-8 but showed them the same way as the Web App.
Recreating them with Visual Studio Code somehow solved the problem.
Thanks for you help

**Comment by RickStrahl** [comment]
I'm guessing the file wasn't actually saved with the encoding byte marks. I can't remember the proper sequence there, but if you use Visual Studio or VS Code with UTF-8 encoding on the file it should work. Certainly did when I tested and saved the sample file (in VS 2019).

I think one of the issues could be UTF-8 with a BOM or without. The default tends to be with a BOM (ie a few bytes of preamble before the doc starts). You can control this if you use the Markdown.File() helper where you can specify the encoding if necessary (but then knowing what that is is very difficult).


File encoding can be a pain - that's why at this point I think there's NEVER a reason not to save a file in UTF-8 format.
