### ISSUE TITLE
Support for .NET Standard 2.1

### ISSUE THREAD

**Issue by RichCerone** [RickStrahl/Westwind.AspNetCore.Markdown#25]
Hello, I noticed that the later versions of this library use .NET Core 3.1 instead of .NET Standard 2.1. Is there a specific reason for this? We are looking to use this package, but considering that .NET Core 3.1 will eventually become EOL in the next 2 years, we would be stuck with no upgrade path.

**Comment by RickStrahl** [comment]
It was never a .NET Standard library because it has dependencies on ASP.NET Core. There was support for .NET Core 2.1 but pulled that out. 

.NET 3.1 libraries work in .NET Core 5.0 so forward compatibility isn't an issue. But - I'll be adding an explicit .NET Core 5.0 target when I get a chance. It's more for optics than for real use case since there likely won't even be any changes other than the additional target and the 3.1 lib works fine in 5.0.

**Comment by RickStrahl** [comment]
FWIW, I try to follow the .NET policy of supporting the last LTS version back from the current version.

The reason I pulled the 2.1 version was primarily because it has some missing interfaces that make the code a lot more messy than it should be. So 2.1 is no longer supported but one can always use the older version for that.
