### ISSUE TITLE
Use bootstrap attributes

### ISSUE THREAD

**Issue by dbogatov** [RickStrahl/Westwind.AspNetCore.Markdown#3]
Is it possible to include bootstrap classes into generated elements, such as 
```html
<blockquote class="blockquote">...</blockquote>
```

Or can I define custom rules, like which classes to add to which elements?

**Comment by RickStrahl** [comment]
You can embed raw HTML into your Markdown - Markdown is a superset of HTML essentially (with some quirks but mostly it works) so you can wrap your expressions with raw markdown.

Otherwise Markdown has no support for adding custom styles or classes to definitions directly.

You can't change what gets generated (like adding a class) but you can customize the CSS that is used to render the quotes. That of course depends on the host page and the style sheet it uses. As to blockquotes I think the only option you have there is to use generic CSS styling for `blockquote` or `#MyElement blockquote`.
